import React from 'react';
import { useMarket } from '../context/MarketContext';
import { 
  TrendingUp, 
  TrendingDown, 
  Globe, 
  DollarSign, 
  Activity, 
  Coffee, 
  ShieldAlert, 
  Bone, 
  ArrowUpRight,
  PieChart as PieIcon
} from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip } from 'recharts';

export const EconomyPage: React.FC = () => {
  const { formatMoney } = useMarket();

  const gdpHistory = [
    { year: '2021', gdp: 28.4 },
    { year: '2022', gdp: 34.1 },
    { year: '2023', gdp: 39.8 },
    { year: '2024', gdp: 44.2 },
    { year: '2025', gdp: 45.6 },
    { year: '2026 (Est.)', gdp: 48.72 },
  ];

  const indicators = [
    { label: 'National Poop Output', val: '482,910 KG', change: '+5.4%', icon: '💩', desc: 'Total estimated physical yard deposits across domestic zones.' },
    { label: 'Treat Inflation Rate', val: '8.4%', change: '+1.2%', icon: '🦴', desc: 'Rising cost of peanut butter biscuits and dried liver treats.' },
    { label: 'Average Bark Rate', val: '142 BARK/HR', change: '+8.9%', icon: '🔊', desc: 'Composite neighborhood acoustic disturbance index.' },
    { label: 'Park Unemployment', val: '3.1%', change: '-0.4%', icon: '🌳', desc: 'Proportion of dogs failing to report to outdoor grass daily.' },
    { label: 'Dog Confidence Index', val: '88.4 / 100', change: '+2.1%', icon: '🤝', desc: 'Canine optimism regarding dinnertime scrap distribution.' },
    { label: 'Composite Bone Price', val: '₹42.80', change: '+3.6%', icon: '🍖', desc: 'Average spot price for smoked femur marrow contracts.' },
    { label: 'Cat Threat Warning Level', val: '76.2 / 100', change: '+14.5%', icon: '🐈', desc: 'Aggregate fence-line feline presence index.' },
    { label: 'Total Nap GDP', val: '1.84M HRS', change: '+0.8%', icon: '🛋️', desc: 'Gross Domestic Sleeping registered on velvet couches.' },
  ];

  return (
    <div className="space-y-6 font-mono text-xs">
      {/* Header */}
      <div className="pb-4 border-b border-slate-800">
        <h1 className="text-xl font-bold text-slate-100 flex items-center">
          <Globe className="w-5 h-5 text-emerald-400 mr-2" />
          Canine Macroeconomic Indicators & Poop GDP
        </h1>
        <p className="text-xs text-slate-400 mt-1">
          National accounts, digestion aggregates, and fiscal health of the global canine economy.
        </p>
      </div>

      {/* POOP GDP Flagship Card */}
      <div className="bg-gradient-to-br from-[#0c1322] via-[#090e18] to-[#070a12] border-2 border-emerald-500/50 rounded-xl p-6 relative overflow-hidden shadow-2xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2 max-w-xl">
            <div className="inline-flex items-center space-x-2 bg-emerald-950/80 border border-emerald-800 px-3 py-1 rounded-full text-[11px] text-emerald-400 font-bold">
              <span>CANINE GROSS DOMESTIC PRODUCT</span>
            </div>
            <div className="text-3xl sm:text-4xl font-extrabold text-slate-100">
              POOP GDP: ₹48.72M
            </div>
            <div className="inline-flex items-center text-xs font-bold text-emerald-400 bg-emerald-950/60 px-2 py-0.5 rounded border border-emerald-700/80">
              <ArrowUpRight className="w-3.5 h-3.5 mr-0.5" /> ▲ +6.82% Year-over-Year
            </div>
            <p className="text-slate-300 font-sans text-xs leading-relaxed mt-2 italic">
              “The estimated total economic value of fictional dog poop generated by the fictional canine economy. Driven predominantly by morning walk efficiencies and high-grade organic kibble conversion.”
            </p>
          </div>

          {/* Historical Mini Chart */}
          <div className="w-full md:w-72 h-40 bg-[#080c14] border border-slate-800 rounded-lg p-3">
            <div className="text-[10px] text-slate-500 mb-1">HISTORICAL POOP GDP (₹ CRORES)</div>
            <ResponsiveContainer width="100%" height="85%">
              <AreaChart data={gdpHistory} margin={{ top: 5, right: 5, left: -25, bottom: 0 }}>
                <XAxis dataKey="year" stroke="#475569" fontSize={9} />
                <YAxis stroke="#475569" fontSize={9} domain={[25, 55]} />
                <Tooltip contentStyle={{ backgroundColor: '#0f172a', borderColor: '#334155', fontSize: '11px' }} />
                <Area type="monotone" dataKey="gdp" stroke="#22c55e" fill="#10b981" fillOpacity={0.25} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* 8 Macro Economic Metrics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {indicators.map(ind => (
          <div key={ind.label} className="bg-[#0b101c] border border-slate-800 rounded-lg p-4 space-y-2 hover:border-slate-700 transition-colors">
            <div className="flex items-center justify-between">
              <span className="text-xl">{ind.icon}</span>
              <span className="text-[10px] font-bold text-emerald-400 bg-emerald-950/60 px-1.5 py-0.5 rounded border border-emerald-900/60">
                {ind.change}
              </span>
            </div>
            <div>
              <div className="text-lg font-bold text-slate-100">{ind.val}</div>
              <div className="text-[10px] text-slate-400 uppercase tracking-wider font-semibold">{ind.label}</div>
            </div>
            <p className="text-[10px] text-slate-500 font-sans leading-snug pt-1 border-t border-slate-850">
              {ind.desc}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
};
